#!/usr/bin/env python
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Richard Tuin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

import yaml
import subprocess
import os
import re
import sys

installed = 0
for root, dirs, files in os.walk('roles'):
    for file in files:
        filePath = os.path.join(root, file)
        if re.findall("meta/main.yml$", filePath):

            stream = open(filePath, 'r')
            data = yaml.load(stream)

            process = subprocess.Popen(["ansible-galaxy", "list"], stdout=subprocess.PIPE)
            installedDeps = process.communicate()[0]
            installedDepsList = re.findall("^\s([^,]*)", installedDeps, re.M)
            requiredDeps = data["dependencies"]
            if requiredDeps:
                for item in requiredDeps:
                    if not item in installedDepsList and not os.path.isdir("roles/" + item):
                        subprocess.call(["sudo", "ansible-galaxy", "install", item])
                        installed += 1

if installed == 0:
    print "All Ansible galaxy dependencies already installed"
